apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: arjunkv
spec:
  provider: azure
  parameters:
    keyvaultName: arjunkv
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: 63045d97-94b7-4e69-909a-cb2817caaf6e
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: ExampleSecret
          objectType: secret
          objectVersion: ""
    tenantId: "6314d190-bc3b-42a9-af4f-de8175130f73"
    
    
